<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-27 at 10:59:34.
 */
class encuestaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var encuesta
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new encuesta;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers encuesta::ClientBrowser
     * @todo   Implement testClientBrowser().
     */
    public function testClientBrowser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers encuesta::Form
     * @todo   Implement testForm().
     */
    public function testForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers encuesta::getPregunta
     * @todo   Implement testGetPregunta().
     */
    public function testGetPregunta() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
